device:
  - name: "(?i)^8BitDo.*gamepad Keyboard$"
    bind:
      PageUp: prev_page
      PageDown: next_page
      G: next_page # A button
      J: next_page # B button
      H: prev_page # X button
      I: prev_page # Y button

      # D pad
      C: rotate_ccw # Up
      D: rotate_cw # down

      N: brightness_down # minus
      O: brightness_up # plus

      L: warmth_down # L2
      R: warmth_up # R2

  - name: "(?i)^8BitDo.*gamepad$"
    bind:
      PageUp: prev_page
      PageDown: next_page
      A: next_page
      B: next_page
      X: prev_page
      Y: prev_page
      Start: brightness_up
      Select: brightness_down
      TL2: warmth_down
      TR2: warmth_up
      # D pad
      DPad_Up: rotate_ccw
      DPad_Down: rotate_cw
